name: Generate Snake
on:
  push:
    branches: [main]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm run build:action
      - name: Run action
        uses: ./packages/action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: edwardvey
      - name: Move and commit SVG
        run: |
          mkdir -p output
          mv github-contribution-grid-snake.svg output/ || true
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update snake SVG" || echo "No changes to commit"
          git push
