jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run snake generator
        run: npx ts-node snake.ts

      - name: Commit generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
          new_branch: output # or omit for main
          force: true # only needed if dist/ remains in .gitignore
