name: Generate Custom Snake

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run snake generator
        run: npx ts-node snake.ts

      - name: Commit generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
          branch: output
