name: Generate Custom Snake

permissions:
  contents: write # ← allow pushes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Install dependencies
        run: npm ci

      - name: Run snake generator
        run: npx ts-node snake.ts

      - name: Commit generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
          new_branch: output
          push: true
